CATEGORY_FIGHTER = "Fighter"
CATEGORY_STAGE = "Stage"
CATEGORY_EFFECTS = "Effects"
CATEGORY_UI = "UI"
CATEGORY_PARAM = "Param"
CATEGORY_AUDIO = "Audio"
CATEGORY_MISC = "Misc"
CATEGORIES = [CATEGORY_FIGHTER, CATEGORY_STAGE, CATEGORY_EFFECTS, CATEGORY_UI, CATEGORY_PARAM, CATEGORY_AUDIO, CATEGORY_MISC]