from enum import Enum

class BaseEnum(str, Enum):
    def __str__(self):
        return str(self.value)
    
    @classmethod
    def list(cls):
        return [e.value for e in cls]

class Theme(BaseEnum):
    DARK = "dark"
    LIGHT = "light"

class ListLayout(BaseEnum):
    LIST = "list"
    GRID = "grid"

class Wifi(BaseEnum):
    SAFE = "Safe"
    UNCERTAIN = "Uncertain"
    UNSAFE = "Not Safe"

class InfoToml(BaseEnum):
    INCLUDED = "Included"
    NOT_INCLUDED = "Not Included"

class Visibility(BaseEnum):
    VISIBLE = "Visible"
    HIDDEN = "Hidden"

class EnabledState(BaseEnum):
    ENABLED = "Enabled"
    DISABLED = "Disabled"

class Category(BaseEnum):
    FIGHTER = "Fighter"
    STAGE = "Stage"
    EFFECTS = "Effects"
    UI = "UI"
    PARAM = "Param"
    AUDIO = "Audio"
    MISC = "Misc"

class Element(BaseEnum):
    SKIN = "Skin"
    RECOLOR = "Recolor"
    MOTION = "Motion"
    ALL_EFFECT = "Effect"
    ONE_EFFECT = "Single Effect"
    VOICE = "Voice"
    SOUND = "SFX"
    NARRATOR = "Narrator Voice"
    V_THEME = "Custom Victory Theme"
    V_ANIMATION = "Custom Victory Animation"
    ALL_NAME = "Custom Name"
    ONE_NAME = "Single Custom Name"
    UI = "UI"
    KIRBY_HAT = "Kirby"
    STAGE = "Stage"
    ITEM = "Item"
    MOVESET = "Moveset"
    FINAL_SMASH = "Final Smash"

class Fighter(BaseEnum):
    MARIO="mario"
    DONKEY="donkey"
    LINK="link"
    SAMUS="samus"
    SAMUSD="samusd"
    YOSHI="yoshi"
    KIRBY="kirby"
    FOX="fox"
    PIKACHU="pikachu"
    LUIGI="luigi"
    NESS="ness"
    CAPTAIN="captain"
    PURIN="purin"
    PEACH="peach"
    DAISY="daisy"
    KOOPA="koopa"
    KOOPAG="koopag"
    NANA="nana"
    POPO="popo"
    SHEIK="sheik"
    ZELDA="zelda"
    MARIOD="mariod"
    PICHU="pichu"
    FALCO="falco"
    MARTH="marth"
    LUCINA="lucina"
    YOUNGLINK="younglink"
    GANON="ganon"
    MEWTWO="mewtwo"
    ROY="roy"
    CHROM="chrom"
    GAMEWATCH="gamewatch"
    METAKNIGHT="metaknight"
    PIT="pit"
    PITB="pitb"
    SZEROSUIT="szerosuit"
    WARIO="wario"
    SNAKE="snake"
    IKE="ike"
    PTRAINER="ptrainer"
    SQUIRTLE="pzenigame"
    IVYSAUR="pfushigisou"
    CHARIZARD="plizardon"
    DIDDY="diddy"
    LUCAS="lucas"
    SONIC="sonic"
    DEDEDE="dedede"
    PIKMIN="pikmin"
    LUCARIO="lucario"
    ROB="robot"
    TOONLINK="toonlink"
    WOLF="wolf"
    MURABITO="murabito"
    ROCKMAN="rockman"
    WIIFIT="wiifit"
    ROSALINA="rosetta"
    LITTLEMAC="littlemac"
    GRENINJA="gekkouga"
    MIIFIGHTER="miifighter"
    MIISWORDSMAN="miiswordsman"
    MIIGUNNER="miigunner"
    PALUTENA="palutena"
    PACMAN="pacman"
    REFLET="reflet"
    SHULK="shulk"
    KOOPAJR="koopajr"
    DUCKHUNT="duckhunt"
    RYU="ryu"
    KEN="ken"
    CLOUD="cloud"
    CORRIN="kamui"
    BAYONETTA="bayonetta"
    INKLING="inkling"
    RIDLEY="ridley"
    SIMON="simon"
    RICHTER="richter"
    KROOL="krool"
    ISABELLE="shizue"
    INCINEROAR="gaogaen"
    PIRANA="packun"
    JOCKER="jack"
    HERO="brave"
    BANJO="buddy"
    TERRY="dolly"
    BYLETH="master"
    MINMIN="tantan"
    STEVE="pickel"
    SEPHIROTH="edge"
    PYRA="eflame"
    REX="element"
    MYTHRA="elight"
    KAZUYA="demon"
    SORA="trail"

class Series(BaseEnum):
    TEKKEN="Tekken"
    DONKEYKONG="Donkey Kong"
    ICECLIMBER="Ice Climber"
    BANJOKAZOOIE="Banjo-Kazooie"
    PACMAN="Pac-Man"
    CASTLEVANIA="Castlevania"
    MII="Mii"
    BAYONETTA="Bayonetta"
    GAMEWATCH="Game & Watch"
    DRAGONQUEST="Dragon Quest"
    PERSONA="Persona"
    METALGEARSOLID="Metal Gear Solid"
    SONIC="Sonic"
    SPLATOON="Splatoon"
    ANIMALCROSSING="Animal Crossing"
    KIDICARUS="Kid Icarus"
    EARTHBOUND="EarthBound"
    PIKMIN="Pikmin"
    SUPERMARIO="Super Mario"
    KIRBY="Kirby"
    WARIOWARE="WarioWare"
    ARMS="Arms"
    WIIFIT="Wii Fit"
    FATALFURY="Fatal Fury"
    FINALFANTASY="Final Fantasy"
    METROID="Metroid"
    STREETFIGHTER="Street Fighter"
    FIREEMBLEM="Fire Emblem"
    ZELDA="Zelda"
    MEGAMAN="Mega Man"
    KINGDOMHEARTS="Kingdom Hearts"
    PUNCHOUT="Punch-Out"
    ROB="R.O.B"
    MINECRAFT="Minecraft"
    STARFOX="StarFox"
    FZERO="F-Zero"
    XENOBLADE="Xenoblade"
    DUCKHUNT="Duck Hunt"
    POKEMON="Pokemon"