WARNING = "Warning"
INFO = "Info"
WARNING_DEFAULT_WORKSPACE_DELETE = "The default workspace cannot be removed."
INFO_DRAG_DROP_COPY_COMPLETE = "Successfully copied contents into mod directory!"
ASK_WORKSPACE_DELETE = "Remove the selected workspace(s)?"
ASK_PRESET_SAVE = "A total of {0} mods were activated for the preset '{1}'.\nSave pending changes?"
TITLE_WORKSPACE_DELETE = "Remove Workspace"
TITLE_PRESET_SAVE = "Save Preset"
